# Generated by Django 4.0.1 on 2022-01-26 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentKey', models.IntegerField(unique=True)),
                ('departmentName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.IntegerField(unique=True)),
                ('employeeName', models.CharField(max_length=100, unique=True)),
                ('dob', models.DateField()),
                ('employeeEmail', models.EmailField(max_length=254, unique=True)),
                ('departmentKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DatabaseApp.department')),
            ],
        ),
    ]
