# Generated by Django 4.0.1 on 2022-01-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departmentKey',
            new_name='departmentName',
        ),
    ]
