# Generated by Django 4.0.1 on 2022-01-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApp', '0002_rename_departmentkey_employee_departmentname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departmentName',
            new_name='department_Key',
        ),
    ]
