# Generated by Django 4.0.1 on 2022-01-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApp', '0003_rename_departmentname_employee_department_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('employeeID', 'department_Key')},
        ),
    ]
