# Generated by Django 4.0.1 on 2022-01-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApp', '0004_alter_employee_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='department',
            name='departmentKey',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
